/**
 * The settings catalog: what the assistant knows about the app's own settings.
 *
 * A representative (not exhaustive) set, declared once. It feeds two things: the
 * read-only `setting` entity (so the assistant can explain "what does X do") and the
 * `navigate` tool (so it can deep-link the user straight to the control + highlight
 * it). `tab` is the settings tab the control lives in; `anchor` is the data-setting
 * value the client scrolls to and flashes (best-effort; the tab opens regardless).
 *
 * Adding a setting here makes it both explainable and navigable with no other edits.
 */
export type SettingsTab = 'general' | 'connection' | 'interface' | 'advanced' | 'security' | 'engines' | 'audio' | 'promptBuilder' | 'regex';

export interface SettingDef {
	id: string;
	label: string;
	describe: string;
	tab: SettingsTab;
	anchor: string;
}

export const SETTINGS: SettingDef[] = [
	// General
	{ id: 'message-drafts', label: 'Message Drafts', describe: 'Whether unsent text in the chat box is saved per chat (and synced across devices). A draft sticks around until the message is sent or the box is emptied.', tab: 'general', anchor: 'message-drafts' },
	{ id: 'input-history', label: 'Input History', describe: 'Whether the Up/Down arrow keys recall previously sent messages while the chat box is empty. Entries are kept in their own log, so they survive a message or chat being deleted. Controls here: recall scope (all chats, which is the default, or the current chat only), how many entries are kept (10–1000, oldest trimmed first), and a button to clear the whole history. Keyboard only: not available on touch devices.', tab: 'general', anchor: 'input-history' },
	{ id: 'long-chats', label: 'Long Chats', describe: 'Whether a chat opens on its newest turns rather than rendering its whole branch at once, which is what makes a long story slow to open and slow to stream on an older machine. Controls here: the switch, how many turns each load brings in (10–1000, default 100, which is both the opening window and every step back from it), and whether earlier turns arrive on their own as the reader scrolls back or from a button at the top of the loaded stretch. It limits rendering only: the whole branch is still in memory, still what the prompt is assembled from, and still what find in chat searches (a hit further back loads the turns it needs). The story map, the chats panel and its previews are never limited.', tab: 'general', anchor: 'long-chats' },
	{ id: 'autoscroll', label: 'Autoscroll', describe: 'Whether the chat follows a reply down the screen while it streams. On (the default), the view stays on the newest line for as long as the reader is at the bottom; scrolling up stops it at once, and scrolling back down or the jump arrow at the bottom of the chat picks it up again. Off, the view never moves on its own while a reply is written: a reader at the bottom still sees the message they sent and the start of the reply, everything after that waits below, and the jump arrow shows once there is more to read.', tab: 'general', anchor: 'autoscroll' },
	{ id: 'reasoning', label: 'Reasoning', describe: 'Auto-expand opens the collapsible Reasoning box by default while streaming and on saved messages. Whether inline reasoning markers are parsed out of replies is a per-connection setting: a connection\'s Response card on the Connections page.', tab: 'general', anchor: 'reasoning' },
	{ id: 'assistant-button', label: 'Floating Assistant Button', describe: 'Whether the floating Chungus Assistant button sits in the corner of the workspace. Off hides the button and nothing else: sessions, a running turn and every assistant setting are untouched, and Ctrl/Cmd+J opens and closes the panel either way. That button is also where a running turn, a turn waiting for approval and a just-finished one show themselves, so with it hidden those are visible only inside the panel.', tab: 'general', anchor: 'assistant-button' },
	{ id: 'library-open-chat', label: 'Library', describe: 'Whether the Library carries a row naming what the open chat is played with: on the Characters shelf the character it plays, on the Personas shelf the persona it is played as, each one press from that entry in the Library editor. Off by default. The row sits above the browse bar rather than in the list, so nothing is reordered and no filter, sort or page can hide it. It is absent while no chat is open, while the entry it would name has been deleted, and while the New chat flow or a bulk selection is using the top of the panel.', tab: 'general', anchor: 'library-open-chat' },
	{ id: 'story-map-scroll', label: 'Story Map Scrolling', describe: 'What a plain mouse wheel or two-finger trackpad scroll does on the story map canvas: off (the default) it zooms in and out, on it moves the map around. The other gestures are the same either way: a trackpad pinch and Ctrl/Cmd+scroll zoom around the cursor, Shift+scroll slides sideways, and the canvas keeps its own zoom buttons in the corner. Only the story map is affected; nothing else in the app reads this.', tab: 'general', anchor: 'story-map-scroll' },
	// Audio
	{ id: 'notification-sounds', label: 'Notification Sounds', describe: 'Whether a short tone plays when it is the reader\'s turn again (a reply written, an assistant turn ended, a question waiting to be answered), and off by default: an app that has never made a sound does not start making one because it updated. The switch here opens the rest of the page. "When to play" decides whether a tone waits for this window to lose focus (the default) or plays even while the reader is looking at the app, and Volume rides on top of a per-tone loudness correction, so the nine bundled tones sit at the same level however loud their authors recorded them. Moving the slider plays the tone that was heard last, at the level it settles on. One limit is stated on the card rather than hidden: leaving the browser entirely on a phone puts the page to sleep, and a sleeping page cannot make a sound, so tones reach a reader who is in another tab or behind another window rather than one who has left the app.', tab: 'audio', anchor: 'notification-sounds' },
	{ id: 'sound-events', label: 'Sound Events', describe: 'Which moments make a sound and which tone each one uses: a reply finished (a story reply, a continuation or an opening scene), the assistant finished a turn, the assistant stopped to ask for approval or an answer, and something failed (a reply or an assistant turn). A row opens on the nine bundled tones plus None; tapping one plays it and assigns it in the same press, which is also what lets a browser make sound at all, since every browser demands an interaction first. None silences that one event while the others keep playing. Nothing plays for an ending the reader caused: a reply they stopped, or a turn they cancelled. Present only while Notification Sounds is on.', tab: 'audio', anchor: 'sound-events' },
	{ id: 'soundscape', label: 'Soundscape', describe: 'A mix of ambient recordings played underneath the story, built by hand: rain on a window, a crowded bar, a campfire and more, on shelves (Nature, Rain, Places, Transport, Urban). There is one mix for the whole app rather than one per chat, and it never follows the scene on its own. Pressing a recording adds it and unfolds its level slider and two placement buttons; pressing it again takes it out, and Clear all empties the mix after asking. Any number can play at once. "Behind a wall" takes the top end off, the way a wall, a window or a hull does; "Far away" sets it back with the space in between audible; each works alone or with the other. Overall Level sits above the list and three switches below it: "Loop without an audible seam" (on by default; off, most recordings click at every wrap), "Match every recording\'s loudness" (on by default; evens out recordings published at very different levels, though never far enough to make one clip, so a few of the most dynamic stay quieter) and "Let levels drift on their own" (off by default; each level wanders a few decibels around where it was set, shown as a thin mark on its slider while the thumb stays put). Nothing plays until a play button is pressed: the card\'s own, or the one on the Soundscapes row of the Settings list, which starts and stops the mix without opening the page and lights up while sound is actually coming out. That press is never stored: every page load starts silent, both buttons are unavailable while the mix is empty, emptying the mix stops it, and one device never starts another. The card and that row both say so when the browser is still holding sound back. The mix itself (recordings, levels, placements, switches, overall level) is saved and follows the reader to every device. It is separate from Notification Sounds and plays whether or not that switch is on.', tab: 'audio', anchor: 'soundscape' },
	// Appearance
	{ id: 'palette', label: 'Palette', describe: 'The base palette every other color in the app is derived from, the six shipped and every reader-built one in a single grid, plus the text-contrast level (soft/standard/high) as a modifier over whichever is in force. The last cell forks the palette currently worn into one the reader owns and opens its editor below the grid: a name, "Treat these colors as" (dark or light), and the sixteen colors grouped as surfaces, text, lines, story turns and status. That dark/light answer is not a label: it decides how far translucent surfaces may go, which way shadows and the story halo are mixed, and what glyphs a phone paints its status bar. Changes apply live to the whole app as they are picked, so the editor closes on a bar of full-size buttons rather than a link: Done keeps everything, Discard changes puts the palette back exactly as the editor found it, and the left button reads Cancel on a palette forked minutes ago (removing it and putting the previous one back on) or Delete palette on one that already existed. The editor also measures itself, showing WCAG contrast for the pairs the app actually puts ink on (body text owes 4.5:1, supporting text 3:1); it reports rather than refuses. The one palette color no editor offers is the modal scrim, which answers to the mode alone. Deleting a palette that the app is wearing says so before the press: the look falls back to Graphite and the interface repaints.', tab: 'interface', anchor: 'palette' },
	{ id: 'interface-defaults', label: 'Restore Interface Defaults', describe: 'One link at the foot of the Interface page, the only way back to the shipped look for that half of it. It puts palette, accent, interface font, corners and glass back to what the app ships with, and asks first, naming what goes. The background image, the ambient mix and every Chat setting are left alone. Present only while something on the page has actually moved off the default.', tab: 'interface', anchor: 'interface-defaults' },
	{ id: 'chat-defaults', label: 'Restore Chat Defaults', describe: 'One link at the foot of the Chat page, the only way back to the shipped look for that half of it. It puts the reading column, story type, message cards, story text and every message detail back to what the app ships with, and asks first, naming what goes. Interface settings are left alone. Present only while something on the page has actually moved off the default.', tab: 'interface', anchor: 'chat-defaults' },
	{ id: 'accent', label: 'Accent', describe: 'The single hue laid over the palette: eleven presets, each tuned separately for dark and light palettes, or any custom color from a picker. Story text is deliberately not tinted by this unless a Story Text row is set to follow the accent.', tab: 'interface', anchor: 'accent' },
	{ id: 'reading-column', label: 'Reading Column', describe: 'The band the story is read in: chat column width (hidden on phones, where the column is already the whole screen and the knob would be inert), the column shade (how strongly the column is tinted away from whatever sits behind it, always the palette\'s own surface tone and never a color to pick), and how much vertical space sits between turns (compact, cozy, roomy). The background image\'s dim is the other scrim and lives with the image, on Interface.', tab: 'interface', anchor: 'reading-column' },
	{ id: 'story-type', label: 'Story Type', describe: 'The face the story itself is set in: story font, text size, line height and paragraph gap. The interface\'s own font is a separate control on the Interface page, since a knob sits with the thing it dresses.', tab: 'interface', anchor: 'story-type' },
	{ id: 'interface-type', label: 'Interface Type', describe: 'The face the app\'s own chrome is set in: panels, buttons, labels and menus. Nine families, every one of them bundled with the app and served from the reader\'s own machine rather than a font service; the default loads at startup and any other arrives from the server the first time it is picked. The story\'s own font is a separate control, on Chat, because a knob sits with the thing it dresses.', tab: 'interface', anchor: 'interface-type' },
	{ id: 'surfaces', label: 'Surfaces', describe: 'How every surface in the app is cut and how heavy it feels. Corners rounds all of them, the message card included (the card carries a second rounding of its own on top of this one, on Chat). Glass blur (off/subtle/full, full by default) decides how much of what sits behind a surface shows through it and how hard the blur is; every surface follows it together, and a light palette deliberately keeps far less transparency than a dark one at the same setting, because a translucent surface drifts toward what is behind it and the same glass gains contrast for light text while losing it for dark. Reduce animations cuts every interface animation and transition to nothing; the operating system\'s own reduce-motion preference does the same without this being touched, and ambient effects are drawn on a canvas and are not covered by either.', tab: 'interface', anchor: 'surfaces' },
	{ id: 'split-view', label: 'Split Settings View', describe: 'On screens wide enough to dock Settings (1700px and up), the panel splits macOS-style: the dock keeps the section list and the selected page opens in a wide centered panel. Off keeps the phone-style drill-down everywhere. Does nothing below dock widths, where Settings is a single centered overlay.', tab: 'general', anchor: 'split-view' },
	{ id: 'chat-style', label: 'Chat Style', describe: 'How chat turns render: Bubbles (cozy chat bubbles, you on the right and them on the left), Flat (the same bubbles with both portraits down the left, so the story reads as one column), Portraits (forum-log cards with large portraits, every turn full width), or Manuscript (bare prose, no cards, no avatars). It also decides which of the other Chat cards apply: Manuscript draws no card and no portrait, so the shape, color and portrait cards are hidden while it is active; Bubbles and Flat share every card knob.', tab: 'interface', anchor: 'chat-style' },
	{ id: 'message-shape', label: 'Message Shape', describe: 'The geometry of a message card: corner rounding (its own multiplier, on top of the global Corners knob), inner padding (compact/normal/roomy), outline weight (none/hairline/bold), and shadow (none/soft/lifted). Bubbles-only extra: card width as a fraction of the chat column.', tab: 'interface', anchor: 'message-shape' },
	{ id: 'message-colors', label: 'Message Colors', describe: 'Per-role message card color. Each role gets a tint color plus a strength slider: the tint MIXES into the palette\'s own bubble color instead of replacing it, so switching themes carries the tint along and text never lands on an unreadable card. Also here: card opacity (a multiplier riding on top of the Glass setting, not a replacement for it) and an optional left accent rail on character turns (Bubbles only).', tab: 'interface', anchor: 'message-colors' },
	{ id: 'message-avatars', label: 'Portraits', describe: 'The speaker portrait beside each turn: show or hide, silhouette (portrait 2:3, square, or circle; Bubbles only, since the Portraits chat style owns its own in-card frame), and size. With portraits off, the message number and generation timer move into the meta row instead of disappearing with the portrait.', tab: 'interface', anchor: 'message-avatars' },
	{ id: 'story-text', label: 'Story Text', describe: 'How the markup inside a turn reads, judged on a live sample of real story text rather than a drawing. Quoted speech, emphasis and strong text get one line each, carrying the same three controls: a color swatch, a bold B and an italic I. Neither letter pressed is the prose\'s own face, so an accent can be reduced to plain text while keeping its color, or colored while staying plain; dialogue ships with neither, emphasis with I, strong text with B. Clicking the swatch opens where the color comes from, each option shown in the color it means: Off (the color of the prose around it, the markup still renders but stops being tinted), Default (the shipped tint), Accent (follows the theme accent as it changes) and Custom (a picker; used exactly as picked and never mixed). This card is the one place story text is colored. It also carries Text shadow, a whole-card legibility halo behind the prose for stories read over a background image or a card faded to nothing: dark behind light text, light behind dark, never a color to pick.', tab: 'interface', anchor: 'story-text' },
	{ id: 'message-chrome', label: 'Speaker & Controls', describe: 'The speaker name above a turn and the controls under it. Name: show it or not, its chrome (an outlined pill or plain text) and small caps as a separate switch, so any combination works (Manuscript keeps its own label whatever is picked). Controls: whether the edit/copy/retry/delete buttons show on hover, always, or never, a Compact switch that drops their word labels down to icons only (phones are always icon-only regardless), a Keep actions in view switch that keeps the buttons of a long turn within reach while it scrolls (the row of buttons sticks to the bottom of the view while the turn is on screen), whether the branch swipe arrows are always visible or hover-only, and how faint a turn goes once it has been folded into chat memory. That last slider appears only while the Chat Memory engine is on, since nothing is ghosted without it.', tab: 'interface', anchor: 'message-chrome' },
	{ id: 'message-details', label: 'Message Details', describe: 'Which per-message extras show in the chat transcript: position numbers under each portrait (#1, #2, renumbering on delete), timestamps, the provider/model info, message token counts, the reasoning block\'s own token estimate (a separate toggle), and the generation timer (live while streaming, then locked to the turn). Timestamps also carry a format: Relative ("5 minutes ago", which ticks on its own), Short, or Full, plus a 12/24-hour clock override; the language and date order always come from the browser, never a fixed locale.', tab: 'interface', anchor: 'message-details' },
	{ id: 'chat-scene', label: 'Scene', describe: 'Which scene the Background and Ambient Effects cards below it edit: the app-wide one every chat wears, or the open chat\'s own. A chat picking its own starts from a copy of what is on screen, so the switch itself changes nothing, and switching back keeps that scene for the way back rather than throwing it away. "This chat" is unavailable while no chat is open. The note under the pills says how many chats an app-wide change will not reach.', tab: 'interface', anchor: 'chat-scene' },
	{ id: 'background', label: 'Background', describe: 'A picture behind the whole workspace (bundled defaults or your own upload), with dim and blur controls for readability. Dim is always plain black, whatever the palette: it is a photographic scrim, and darkening a picture is what a dim is. Ambient effects and panels layer on top of it. Both controls appear only once an image is set. The reading column\'s own shade is the other scrim and lives with the column, on Chat.', tab: 'interface', anchor: 'background' },
	{ id: 'ambient-effects', label: 'Ambient Effects', describe: 'The ambient mixer: a live stage previewing the atmosphere (rain, snow, fog, embers and more) over the current workspace background, a grouped catalog where a tap adds or removes an effect (any number stack), and a row per active effect that opens on that effect\'s own knobs. There is no whole-mix cluster: every knob belongs to one effect. Each row carries density, speed, visibility and whether that effect draws over the messages or behind them (double-clicking a slider puts it back to its shipped value), then whatever settings that effect has of its own, like the storm\'s lightning or the rain\'s ground splashes.', tab: 'interface', anchor: 'ambient-effects' },
	// Security
	{ id: 'network-access', label: 'Network Access', describe: 'The master switch over everything else on the Security page, and off by default. It is not a gate but the listening socket itself: while it is off the server opens its port on this computer alone, so a device on the network finds nothing there rather than something that turns it away, and no allowlist entry or password can change that. Flipping it re-opens the port, which drops every live connection including the one this computer is on (the app reconnects by itself). The Device Access and Password Lock cards decide who gets past an open port, so they exist only while it is on.', tab: 'security', anchor: 'network-access' },
	{ id: 'ip-allowlist', label: 'Device Access (IP Allowlist)', describe: 'Control which IP addresses are allowed to reach this ChungusHub instance. A device that tries to connect while blocked appears in a waiting list for one-click allow, and its denied page retries automatically once allowed; devices can also be added manually by address. Allowed devices that are connected right now show a green presence dot. Can be switched off entirely to open the app to every device on the local network; this machine (localhost) is always allowed. Present only while Network Access is on.', tab: 'security', anchor: 'ip-allowlist' },
	{ id: 'password-lock', label: 'Password Lock', describe: 'Optional single shared password other devices must enter before using ChungusHub. This machine (localhost) never needs it. A device stays unlocked while in use and re-locks after a settable stretch of inactivity (a minutes field under the switch, an hour by default, 0 never asking again); setting or changing the password logs every other device out. Recovery when locked out: delete security.json in the data folder. Present only while Network Access is on.', tab: 'security', anchor: 'password-lock' },
	// Connection
	{ id: 'connections', label: 'Connections', describe: 'Named connections and the Model routing card. A connection is a self-contained bundle: provider, its own API key, model, context window, sampling and routing. Model routing is one flat, fully transparent list: every calling point has its own pill picker showing "connection · model". Primary (which writes the story) and Assistant (which runs the Chungus Assistant) come first, then the calling engines (Chat Memory, Opening Scene, Spellcheck, Impersonate). There are no roles, no groups, no defaults-following, no pins, and no quality warnings: each point is bound directly to a connection, a fresh install binds everything to the Default connection, and re-pointing any row is the user\'s own choice. Steering makes no model call and is not listed. Deleting a connection moves anything routed to it onto the first remaining one. Create, duplicate, and delete connections here; open one to edit it.', tab: 'connection', anchor: 'connections' },
	{ id: 'provider', label: 'Provider', describe: 'A connection\'s LLM provider (OpenRouter, OpenAI, and others), chosen in its editor.', tab: 'connection', anchor: 'provider' },
	{ id: 'api-key', label: 'API Key', describe: 'A connection\'s own credentials (API key + base URL), stored server-side and never sent to the client. Two connections can hit the same provider with different keys.', tab: 'connection', anchor: 'api-key' },
	{ id: 'primary-model', label: 'Model', describe: 'The model a connection uses. Whatever is routed to that connection on the Model routing card runs on this model.', tab: 'connection', anchor: 'primary-model' },
	{ id: 'generation', label: 'Sampling Parameters', describe: 'A connection\'s raw sampling parameters, sent with every call that connection serves (story and engines alike): temperature, top_p, top_k, min_p, top_a, repetition/frequency/presence penalties, and an optional fixed seed. Each slider edits the stored value directly and double-click resets it to the default. Controls only appear when the connection actually sends them: hidden parameters never reach the API. For a known provider that follows its documented API; for a bring-your-own OpenAI-compatible endpoint nothing can detect what it accepts, so the same card opens with an "Accepted by this endpoint" chip row the user declares themselves, and the sliders follow that declaration exactly. Nothing in the app overrides these: the Chungus Assistant runs on them too, whenever it is routed to this connection.', tab: 'connection', anchor: 'generation' },
	{ id: 'response-behavior', label: 'Response', describe: 'A connection\'s Response card: Response length (max output tokens), Stream response (token-by-token vs whole message), Auto-parse reasoning (divert inline reasoning markers to the Reasoning box), Reasoning effort (Auto/Off/Minimal→Max), Show reasoning, Verbosity, Send images and Image detail. Each control is hidden when the connection\'s provider or model does not support it.', tab: 'connection', anchor: 'response-behavior' },
	{ id: 'prompt-caching', label: 'Prompt Caching', describe: 'Per-connection prompt caching in the Request card. Where the provider caches on request (Anthropic, OpenRouter), a toggle turns cache-control markers on/off and (where supported) picks a 5-minute or 1-hour cache lifetime; the resent prompt prefix then bills as cache reads (~0.1× input price), a big saving on long chats. Providers that cache automatically (OpenAI, DeepSeek, Grok, Gemini, GLM, …) show an always-on note and cannot be switched off from the API. Default off: caching is opt-in.', tab: 'connection', anchor: 'prompt-caching' },
	{ id: 'context-size', label: 'Context Size', describe: 'A connection\'s cap on total prompt tokens (default 32,768). When a chat outgrows it, the oldest messages are trimmed first. Preset, characters, lorebooks and memory are never cut. It bounds a Chungus Assistant tab the same way: when the connection serving the Assistant is small, an assistant tab drops its oldest turns from working memory sooner.', tab: 'connection', anchor: 'context-size' },
	{ id: 'prompt-post-processing', label: 'Prompt Post-Processing', describe: 'A connection\'s reshaping of the outgoing prompt for APIs with strict message rules: merge consecutive roles (default), enforce a single system message (semi-strict), require a user-first turn (strict), or collapse everything into one user message.', tab: 'connection', anchor: 'prompt-post-processing' },
	// Engines
	{ id: 'engines', label: 'Engines', describe: 'The five built-in AI engines (Chat Memory, Opening Scene, Steering, Spellcheck, and Impersonate) as one calm overview list. Each row shows the engine\'s icon, name, one-line summary, its app-wide on/off switch, and a warning chip only when it spends tokens without being asked (Chat Memory, which runs in the background). Opening a row drills into that engine\'s detail view: its full description, a read-only Model card showing the connection/model/provider it is routed to right now, and its prompt templates edited inline (auto-saved as you type, with a per-field Modified badge and Reset to the shipped default). Turning an engine off keeps its stored data but makes it inert everywhere. The page assigns no connections: every calling engine is routed directly on the Connections page\'s Model routing card, one visible row per engine, no roles or defaults behind it. Steering makes no model call of its own (its guidance rides the story generation), so it has nothing to route; its detail view carries one extra card, Default placement (depth + role), which is what every steering note inherits until that note overrides it. The notes themselves are written from the composer\'s compass popover, not here. Chat Memory\'s per-chat panel lives in the Chat panel\'s Memory tab. Every engine defaults on.', tab: 'engines', anchor: 'engines' },
	// Regex
	{ id: 'regex-rules', label: 'Regex Rules', describe: 'User-defined find & replace rules applied to chat text on the fly. Each rule sets a regex pattern, a replacement, whose messages it touches (yours, the AI\'s, or both), and where it applies: the chat display, the outgoing prompt (what the model sees as history), or both. Saved messages are never modified, so disabling a rule restores the original text. Rules run top to bottom and can be reordered, duplicated, tested live against sample text, exported, and imported. SillyTavern regex scripts import directly. Ships with a starter pack of example rules, every one off by default: strip invisible characters, non-breaking spaces to spaces, em dash to comma (dialogue-dash safe), ellipsis runs to three dots, collapse extra blank lines, and straight double/single quotes. Each rule can carry a short description shown under its name, and a Restore defaults action replaces the whole list with the shipped starter pack.', tab: 'regex', anchor: 'regex-rules' },
	// Prompt builder
	{ id: 'prompt-builder', label: 'Prompt Builder', describe: 'Assemble, order, and tune the structured prompt sent to the model. The preset action menu carries Duplicate, Import JSON file, Export JSON file (downloads it), Copy as JSON (clipboard), Delete and Restore defaults; an export names every per-preset field at its current value, so a shared preset is a complete document. Below the prompt items and the preset controls sits Preset options, three knobs that ride the preset itself: Prune empty blocks (drop a <tag> block when every macro inside it resolves empty), Example separator (what replaces SillyTavern <START> markers between example-dialogue blocks, default ***), and the Continue prompt (the instruction appended after the reply that Continue extends: clear it to send nothing and let providers continue the reply as an assistant prefill; Reset restores the shipped default). All three save and export with the preset.', tab: 'promptBuilder', anchor: 'prompt-builder' }
];

const BY_ID = new Map(SETTINGS.map((s) => [s.id, s]));

export function getSetting(id: string): SettingDef | null {
	return BY_ID.get(id) ?? null;
}
